# Referenced from https://dl.photoprism.app/docker/portainer/stack.yml
# Stack.env defaults come from https://dl.photoprism.app/docker/portainer/stack.env
services:
  photoprism:
    image: photoprism/photoprism:latest
    # restart: unless-stopped
    stop_grace_period: 15s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    env_file:
      - stack.env
    working_dir: "/photoprism"
    volumes:
      - "/mnt/data/photoprism/originals:/photoprism/originals:z"
      - "/mnt/data/photoprism/storage:/photoprism/storage:z"
      - "/mnt/data/photoprism/import:/photoprism/import:z"

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 15s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./database:/var/lib/mysql:z"
    env_file:
      - stack.env