services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
    # To avoid breaking container networking, bind the dns port to the local ip
    # https://discourse.pi-hole.net/t/solve-dns-resolution-in-other-containers-when-using-docker-pihole/31413
      - "LOCAL_IP:53:53/tcp"
      - "LOCAL_IP:53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      # FTLCONF_webserver_api_password: ''
      FTLCONF_dns_rateLimit_count: 2000
    volumes:
      - '/mnt/data/etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
    restart: unless-stopped